Traceback (most recent call last):
  File "skema/program_analysis/model_coverage_report/model_coverage_report.py", line 76, in generate_data_product
    output = func_timeout(10, data_product_function, args=args, kwargs=kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "skema/program_analysis/model_coverage_report/model_coverage_report.py", line 106, in generate_cast
    cast = python_to_cast(source_path, cast_obj=True)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/python2cast.py", line 123, in python_to_cast
    C = convert.visit(contents, {}, {})
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 3545, in visit_Module
    to_add = self.visit(piece, prev_scope_id_dict, curr_scope_id_dict)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 1689, in visit_ClassDef
    self.visit(func, prev_scope_id_dict, curr_scope_id_dict)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 2540, in visit_FunctionDef
    to_add = self.visit(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 729, in visit_Assign
    val = self.visit(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 1121, in visit_BinOp
    right = self.visit(node.right, prev_scope_id_dict, curr_scope_id_dict)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py", line 1425, in visit_Call
    name=arg.value.value.id, id=-1, source_refs=ref
AttributeError: 'Attribute' object has no attribute 'id'
