Traceback (most recent call last):
  File "skema/program_analysis/model_coverage_report/model_coverage_report.py", line 66, in generate_data_product
    output = func_timeout(10, data_product_function, args=args, kwargs=kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "skema/program_analysis/model_coverage_report/model_coverage_report.py", line 103, in generate_cast
    if isinstance(cast, List):
UnboundLocalError: local variable 'cast' referenced before assignment
